name: movies_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #icon
  ionicons:
  cupertino_icons: ^1.0.2

  

  #state management
  flutter_bloc:

  #comparing dart objects
  equatable:

  #service locator
  get_it:

  #dateFormat
  intl:

  #Database
  floor: any

  #make request to api
  retrofit: ^3.0.1
  dio:



  #chached image
  cached_network_image:

  #internet_connection_checker
  internet_connection_checker:

  #connectivity_plus
  connectivity_plus:

  #pull_to_refresh
  pull_to_refresh:

  #lottie
  lottie:

 # for Search Wait typing time 
  #debounce_throttle
  debounce_throttle:

  
  #flutter_screenutil
  flutter_screenutil:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator:
  floor_generator:
  build_runner:
  integration_test:
    sdk: flutter
 
  # unit testing
  mockito: 

  flutter_gen_runner: 

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

  assets:
    # - assets/icons/
    - assets/images/
    - assets/lottie/         
